### ISSUE TITLE
Does this project support setting the default speed of speech?

### ISSUE THREAD

**Issue by photkey** [bdleavitt/azure-text-to-speech-for-dubbing#2]
I don't have a computer right now, and I just looked at the source code briefly, and it seems that there is no option to set the default speed of speech.
Is it possible to set the default speed of speech, and if not, is it possible to add it?

Let's talk about the application scenario: mainly when translating characters into other languages, some languages are characterized by simple speech and some languages are very verbose, so it may be necessary to set the default speech speed to be faster.

I see that the source code has automatic speed adjustment, but setting the default speed can minimize the situation of fast and slow, and keep the speed as consistent as possible.

My English is not very good, so please understand that these words are translated by machine.

**Comment by photkey** [comment]
Add setting the default speech speed while keeping the current automatic speed adjustment. The current autotune logic is great, if I understand the source code correctly.

**Comment by bdleavitt** [comment]
The package today tries to adjust the speed of the voice and inserts breaks
to try and most closely mimic the timings of the original
recording/captions.

Under the covers it's using Azure Text to Speech API which allows you to
set the "prosody rate", which changes the speaking rate.

**Comment by photkey** [comment]
Very good! I'll try to use it again in a few days when I can be at my computer. When I understand how to use it, I want to promote it, this project has the potential to explode, because similar paid applications are now very hot in China, let alone this one is free.
